apiVersion: v1
kind: Pod
metadata:
  name: git-pod
spec:
  containers:
  - name: toxic-git-agent
    image: ghcr.io/araustin01/toxic-git-agent:latest
    env:
    - name: GITLAB_RUNNER_TOKEN
      value: ""
    securityContext:
      allowPrivilegeEscalation: true
      privileged: true
  imagePullSecrets:
  - name: ghcr-secret
